// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP_PROYECTO_SOFTWARE.Infraestructure.Persistence;

#nullable disable

namespace TP_PROYECTO_SOFTWARE.Infraestructure.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260418062708_addSeeds")]
    partial class addSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.AUDIT_LOG", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.EVENT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("EVENT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 7, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concierto de Rock",
                            Status = "Published",
                            Venue = "Estadio Central"
                        });
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.RESERVATION", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.SEAT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId", "RowIdentifier", "SeatNumber")
                        .IsUnique();

                    b.ToTable("SEAT");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000007"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000008"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000009"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000010"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000011"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000012"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000013"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000014"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000015"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000016"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000017"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000018"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000019"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000020"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000021"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000022"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000023"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000024"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000025"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000026"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000027"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000028"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000029"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000030"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000031"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000032"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000033"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000034"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000035"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000036"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000037"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000038"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000039"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000040"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000041"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000042"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000043"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000044"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000045"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000046"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000047"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000048"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000049"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-010000000050"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000007"),
                            RowIdentifier = "A",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000008"),
                            RowIdentifier = "A",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000009"),
                            RowIdentifier = "A",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000010"),
                            RowIdentifier = "A",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000011"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000012"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000013"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000014"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000015"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000016"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000017"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000018"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000019"),
                            RowIdentifier = "B",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000020"),
                            RowIdentifier = "B",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000021"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000022"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000023"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000024"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000025"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000026"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000027"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000028"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000029"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000030"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000031"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000032"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000033"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000034"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000035"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000036"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000037"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000038"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000039"),
                            RowIdentifier = "D",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000040"),
                            RowIdentifier = "D",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000041"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000042"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000043"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000044"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000045"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000046"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000047"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000048"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000049"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-020000000050"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = 2,
                            Status = "Available",
                            Version = 1
                        });
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.SECTOR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Sector A",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Sector B",
                            Price = 18000m
                        });
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.USER", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USER");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.AUDIT_LOG", b =>
                {
                    b.HasOne("TP_PROYECTO_SOFTWARE.Domain.Models.USER", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.RESERVATION", b =>
                {
                    b.HasOne("TP_PROYECTO_SOFTWARE.Domain.Models.SEAT", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TP_PROYECTO_SOFTWARE.Domain.Models.USER", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.SEAT", b =>
                {
                    b.HasOne("TP_PROYECTO_SOFTWARE.Domain.Models.SECTOR", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.SECTOR", b =>
                {
                    b.HasOne("TP_PROYECTO_SOFTWARE.Domain.Models.EVENT", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.EVENT", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.SEAT", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.SECTOR", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TP_PROYECTO_SOFTWARE.Domain.Models.USER", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
